### ISSUE TITLE
shortestPath allShortestPaths  TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by wh6b** [nigelsmall/py2neo#400] opened 2015-04-26 15:41 UTC
Hello all,
I have issue when I try to use shortestPath allShortestPaths in transaction or execute command.

neo4j is neo4j-community-2.1.7
py2neo.\_\_version\_\_ is '2.0.5'

I tried with :
`_req = "start p1=node(121060) , p2=node(124624) match p=shortestPath(p1-[*..10]-p2) return p"`
`_req = "start p1=node(122085) , p2=node(125331) match p=shortestPath((p1)-[*..10]-(p2)) return p"`
`_req = "start p1=node(122085) , p2=node(125331) match p=allShortestPaths((p1)-[*..10]-(p2)) return p"`
on : 
`req = self.graph.cypher.execute(_req)`
or on (same error below) :
`def execute_une_requete(self, _req):`
`    tx = self.graph.cypher.begin()`
`    tx.append(_req)`
`    tx.process()`

Error is :
  File "workload_04/cherche_en_masse.py", line 142, in execute_une_requete
    req = tx.process()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/core.py", line 296, in process
    return self.post(self.__execute or self.__begin)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/core.py", line 267, in post
    for r in result["data"]]))
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 822, in hydrate
    return type(data)(map(self.hydrate, data))
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 801, in hydrate
    start = rel_data["start"]
TypeError: 'NoneType' object has no attribute '__getitem__'

I found solutions like this [one](http://stackoverflow.com/questions/26154104/neo4j-py2neo-neomodel-cypher-shortest-path-giving-error-typeerror-notimp) but cypher.Session doesnt exist anymore in this py2neo version I think.

Thanks in advance.

**Comment by nigelsmall** [comment] 2015-05-18 14:20
I'm unable to recreate this issue. Can you describe for me the type of underlying data that presents this?

**Comment by nigelsmall** [comment] 2015-05-18 14:45
Duplicate of #398 - please consolidate information on this bug there.

**Closed by nigelsmall** 2015-05-18 14:45 UTC
Labels: bug, not enough info
